/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fiestacabservice;

import java.util.ArrayList;

/**
 *
 * @author Tithira
 */

public class Customerfrm extends javax.swing.JFrame {
    

    /**
     * Creates new form Customerfrm
     */
    CustomerDao cdao=new CustomerDao();
    SubsidiaryDao subdao=new SubsidiaryDao();
    public Customerfrm() {
        initComponents();
        fillcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Insertbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mnumtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nmtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        statustxt = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        list1 = new java.awt.List();
        tptxt = new javax.swing.JComboBox<>();
        mnumcheck = new javax.swing.JLabel();
        nmcheck = new javax.swing.JLabel();
        loccheck = new javax.swing.JLabel();
        loctxt = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Insertbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Insertbtn.setText("Insert");
        Insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertbtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Mobile Number");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Location");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Type");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Customer");

        statustxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        statustxt.setForeground(new java.awt.Color(255, 0, 51));
        statustxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchbtn.setText("Search by Mobile number");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        tptxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Business" }));

        mnumcheck.setForeground(new java.awt.Color(255, 51, 51));

        nmcheck.setForeground(new java.awt.Color(255, 51, 51));

        loccheck.setForeground(new java.awt.Color(255, 51, 51));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(139, 139, 139)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mnumtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(nmtxt)
                            .addComponent(tptxt, 0, 211, Short.MAX_VALUE)
                            .addComponent(nmcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loccheck, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnumcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loctxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(searchbtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mnumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mnumcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nmtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nmcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(loctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loccheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(tptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void fillcombo(){
        ArrayList<Subsidiary> sarray=subdao.Searchallsubsidiary();
        for(int i=0;i<sarray.size();i++){
            loctxt.addItem(sarray.get(i).getname());
        }
    }
    private void InsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertbtnActionPerformed
      try{  //button for inserting new Customers
        list1.removeAll();//remove all in the awt list
        mnumcheck.setText("");
        nmcheck.setText("");
        loccheck.setText("");
        statustxt.setText("");
        
        if(mnumtxt.getText().equals("")){//Checking for empty fields
             mnumcheck.setText("Enter the Mobile Number");
        }else if(nmtxt.getText().equals("")){//Checking for empty fields
             nmcheck.setText("Enter the Name");
        }
        else{
            if(mnumtxt.getText().length()!=10){//Checking for Mobile Number Validity
                mnumcheck.setText("Invalid Mobile Number");
            }
            else if((cdao.SearchbytelNo(mnumtxt.getText())).getmnum()==null){//checking whether a customer has already registered.
                Customer cob=new Customer(mnumtxt.getText(), nmtxt.getText(),loctxt.getSelectedItem().toString(),tptxt.getSelectedItem().toString());
                 boolean status=cdao.Insert(cob);
                 if(status==true){
                     statustxt.setText("Insertion Successful");
                     mnumtxt.setText("");
                     nmtxt.setText("");
                     loctxt.setSelectedItem("Colombo");

                 }else{
                     statustxt.setText("Insertion Failed");
                 }
            }else{
                 statustxt.setText("Customer has already Registered");
            }
        }
      }catch(Exception ex){
           statustxt.setText("Error: " +ex);
      }
        
    }//GEN-LAST:event_InsertbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        //button for searching a customer by the mobile number
      try{  
        list1.removeAll();//remove all in the awt list
        mnumcheck.setText("");
        nmcheck.setText("");
        loccheck.setText("");
        statustxt.setText("");
        if(mnumtxt.getText().equals("")){//checking for empty fields
            mnumcheck.setText("Enter the Mobile Number");
        }else{    
           if(mnumtxt.getText().length()!=10){
              mnumcheck.setText("Invalid Mobile Number");
           }else{
             
                  
                Customer cob= cdao.SearchbytelNo(mnumtxt.getText());//searching the customer by the entered mobile number
                if(cob.getmnum()==null){
                     
                     statustxt.setText("Customer Not Found");
                }else{
               //Displaying details about the customer if the customer is available with the entered mob number
                list1.add("Mobile Number:- " +cob.getmnum());
                list1.add("Customer Name:- " +cob.getnm());
                list1.add("Location:- " +cob.getloc());
                list1.add("Type:- " +cob.gettype());
                }
           }
                
               
       }
      }catch(Exception ex){
          statustxt.setText("Error: " +ex);
      }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        mnumcheck.setText("");
        nmcheck.setText("");
        loccheck.setText("");
        statustxt.setText("");
        list1.removeAll();
        
        if(mnumtxt.getText().equals("")){//checking for empty fields
             mnumcheck.setText("Enter the Mobile Number");
        }else if(nmtxt.getText().equals("")){
             nmcheck.setText("Enter the Name");
        }else if(loctxt.getSelectedItem().equals("")){
             loccheck.setText("Enter the Location");
        }
        else{
            if(mnumtxt.getText().length()!=10){
                mnumcheck.setText("Invalid Mobile Number");
            }
            else{
                Customer cob=new Customer(mnumtxt.getText(), nmtxt.getText(),loctxt.getSelectedItem().toString(),tptxt.getSelectedItem().toString());//Creating a customer object
                 boolean status=cdao.update(cob);//passing customer object to the update method in the CustomerDao
                 if(status==true){
                     statustxt.setText("Customer Update Successful");
                     mnumtxt.setText("");
                     nmtxt.setText("");
                     loctxt.setSelectedItem("Colombo");

                 }else{
                     statustxt.setText("Customer Update Failed");
                 }
            }
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        mnumcheck.setText("");
        nmcheck.setText("");
        loccheck.setText("");
        statustxt.setText("");
        list1.removeAll();
        if(mnumtxt.getText().equals("")){
            statustxt.setText("Enter the mobile Number of the Customer");
        }else{
            Customer cob=cdao.SearchbytelNo(mnumtxt.getText());//searching the Customer by the given ID
            if(cob.getmnum()!=null){//checking whether a customer is available with the entered ID
                boolean status=cdao.delete(mnumtxt.getText());
                if(status==true){
                    statustxt.setText("Customer "+cob.getnm()+ " has been Deleted Successfully");
                }else{
                     statustxt.setText("Customer Deletion Failed");
                }
            }else{
                statustxt.setText("Customer not found");
            }
        }
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.hide();
       AdminMenu aob=new AdminMenu();
       aob.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customerfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customerfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.List list1;
    private javax.swing.JLabel loccheck;
    private javax.swing.JComboBox<String> loctxt;
    private javax.swing.JLabel mnumcheck;
    private javax.swing.JTextField mnumtxt;
    private javax.swing.JLabel nmcheck;
    private javax.swing.JTextField nmtxt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLabel statustxt;
    private javax.swing.JComboBox<String> tptxt;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
