/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fiestacabservice;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/**
 *
 * @author Tithira
 */
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
public class UpdateBookingSupfrm extends javax.swing.JFrame {

    /**
     * Creates new form UpdateBookingSupfrm
     */
    VehicleDao vdao=new VehicleDao();
    BookingDao bdao=new BookingDao();
    VasignDao vadao= new VasignDao();
    SubsidiaryDao subdao=new SubsidiaryDao();
    public UpdateBookingSupfrm() {
        initComponents();
        fillcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bidtxt = new javax.swing.JTextField();
        Vregtxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        statustxt = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Vlist1 = new java.awt.List();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Bklist = new java.awt.List();
        spidtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        sbsubtxt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Update Booking(Supervisor)");

        jLabel2.setText("BookingID");

        jButton1.setText("Vehicle Delivered");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hire Ended");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Vehicle Registration Number");

        bidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidtxtActionPerformed(evt);
            }
        });

        Vregtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VregtxtActionPerformed(evt);
            }
        });

        jButton3.setText("Vehicle Returned");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        statustxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statustxt.setForeground(new java.awt.Color(255, 51, 51));
        statustxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton4.setText("Assign Vehicle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Vlist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vlist1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Select Subsidiary:");

        jButton5.setText("Search Available Vehicles/Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        spidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spidtxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter SupervisorID:");

        jButton6.setText("Bookings to Commit/Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        sbsubtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbsubtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(Vregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Vlist1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Bklist, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(sbsubtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(spidtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Bklist, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sbsubtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Vlist1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Vregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    public void fillcombo(){
        ArrayList<Subsidiary> sarray=subdao.Searchallsubsidiary();
        for(int i=0;i<sarray.size();i++){
            sbsubtxt.addItem(sarray.get(i).getname());
        }
    }
    private void bidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidtxtActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Vlist1.removeAll();
        try{
            ArrayList<Vehicle> vlist=vdao.searchvhbysub(sbsubtxt.getSelectedItem().toString());

            for(int j=0;j<vlist.size();j++){

               if(vlist.get(j).getavbty()==true) {
                   Vlist1.add("Registration Number :- " + vlist.get(j).getvid());
                   Vlist1.add("Vehice Model :- " + vlist.get(j).getvModel());
                   Vlist1.add("Vehicle Type :- " + vlist.get(j).getvtype());
                   Vlist1.add("Subsidiary :- " + vlist.get(j).getsdiary());
                   Vlist1.add("Availability :- " + vlist.get(j).getavbty());
                   Vlist1.add("Driver ID :- " + vlist.get(j).getdid());
                   Vlist1.add("----------------------------------------" );
               }

            }
        }catch(Exception ex){
            statustxt.setText("Error");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Bklist.removeAll();
       try{
       ArrayList<Booking> bkarray=bdao.searchbbysupID(spidtxt.getText());//Searching the bookings by the supervisor ID using a method in Bookig Dao Class
       for(int i=0;i<bkarray.size();i++){
           if((bkarray.get(i).getHended())==false){//checking whhether the booking is ended or not
               //if the booking is not ended , data is added to the awt list
               Bklist.add("Customer Mob.Number :- " +bkarray.get(i).getCmob());//Customer Mobile Number
               Bklist.add("BookingID :- " +bkarray.get(i).getbid());//Booking ID
               Bklist.add("Booking Type :- " +bkarray.get(i).getbtype());//Booking Type
               Bklist.add("Customer Location :- " +bkarray.get(i).getloc());//Location of the Customer
               Bklist.add("Destination :- " +bkarray.get(i).getDes());//Destination 
               Bklist.add("Date placed :- " +bkarray.get(i).getDate1());//Date that the Booking was placed
               Bklist.add("Number of Vehicles Needed :- " +bkarray.get(i).getnVh());//Number of vehicles needed for the Booking
               Bklist.add("Vehicle Type :- " +bkarray.get(i).getvtype());//Vehicle Type
               Bklist.add("Date to Deliver :- " +bkarray.get(i).getDatetoDeliver());//Date to deliver the Vehicle
               Bklist.add("SupervisorID :- " +bkarray.get(i).getsid());//Supervisor to guide the booking
               Bklist.add("Vehicle Assigned :- " +bkarray.get(i).getvasgn());//Vehicle Assigned/not
               Bklist.add("-----------------------------------------------");
           }
       }
       }catch(Exception ex){
          statustxt.setText("Error");
       }
       
       
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date date=Calendar.getInstance().getTime();
        DateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
        String sdate=dateformat.format(date);
        
        Booking bob = new Booking();
        bob=bdao.SearchBookingbyID(bidtxt.getText());
        
        bob.setDelivrdD(sdate);
        boolean status=bdao.update(bob);
        if(status==true){
             statustxt.setText("Vehicle Delivery Recorded");
        }else{
            statustxt.setText("Error");
        }
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VregtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VregtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VregtxtActionPerformed

    private void spidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spidtxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Date date=Calendar.getInstance().getTime();
        DateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
        String sdate=dateformat.format(date);
        
        Booking bob = new Booking();
        bob=bdao.SearchBookingbyID(bidtxt.getText());
        
        bob.setRetrnD(sdate);
        boolean status=bdao.update(bob);
        if(status==true){
             statustxt.setText("Vehicle Return Recorded");
        }else{
            statustxt.setText("Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
       try{
            if(bidtxt.getText().equals("")){
                statustxt.setText(" Booking ID  Should be Entered");
            }else{
                Booking bob = new Booking();
                bob=bdao.SearchBookingbyID(bidtxt.getText());
                bob.setHended(true);
                ArrayList<assignVehicle> avl=vadao.SearchAV(bidtxt.getText());
                for(int i=0;i<avl.size();i++){
                    Vehicle vob=vdao.searchVehiclebyID(avl.get(i).getvid());
                    vob.setavbty(true);
                    vdao.Update(vob);
                    
                }
                bdao.update(bob);
                statustxt.setText("Hire Ended");
            }
        }catch(Exception ex){
           statustxt.setText("Error");
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Vlist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vlist1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vlist1ActionPerformed

    private void sbsubtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbsubtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbsubtxtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Booking bk=bdao.SearchBookingbyID(bidtxt.getText());
        bk.setassigned(true);
        Vehicle vob=vdao.searchVehiclebyID(Vregtxt.getText());
        vob.setavbty(false);
        vdao.Update(vob);
        bdao.update(bk);
        assignVehicle vaob=new assignVehicle(bidtxt.getText(), Vregtxt.getText());
        boolean status=vadao.insert(vaob);
        if(status==true){
            statustxt.setText("Vehicle Assigned to the Booking");
        }else{
            statustxt.setText("Vehicle Assigning Error");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBookingSupfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBookingSupfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBookingSupfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBookingSupfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBookingSupfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List Bklist;
    private java.awt.List Vlist1;
    private javax.swing.JTextField Vregtxt;
    private javax.swing.JTextField bidtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> sbsubtxt;
    private javax.swing.JTextField spidtxt;
    private javax.swing.JLabel statustxt;
    // End of variables declaration//GEN-END:variables
}
